server:
    port: 8080

eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
            - id: helloModule
              uri: lb://FIRST-SERVICE
              predicates:
              - Path=/hello/**
            - id: hiModule
              uri: lb://SECOND-SERVICE
              predicates:
              - Path=/hi/**
